version: "3.9"

services:
  app:
    image: jirituryna/incicounter:latest 
    container_name: incicounter
    ports:
      - 8080:8080
    # nakopíruje soubor z hosta soubor ./counter.db do containeru /app/counter.db
    volumes:
      - ./counter.db:/app/counter.db
      
# Persistentní úložiště -> Data z containeru se přepisují do souboru "counter.db" na hostovy
volumes:
  counter.db:


